// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.grpcspringbootx.protobuf;

public interface RequestProductsWithAnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestProductsWithAnimal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
