// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.grpcspringbootx.protobuf;

public interface ResponseProductsWithAnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseProductsWithAnimal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated uint32 product_ids = 1;</code>
   * @return A list containing the productIds.
   */
  java.util.List<java.lang.Integer> getProductIdsList();
  /**
   * <code>repeated uint32 product_ids = 1;</code>
   * @return The count of productIds.
   */
  int getProductIdsCount();
  /**
   * <code>repeated uint32 product_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The productIds at the given index.
   */
  int getProductIds(int index);
}
