// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.grpcspringbootx.protobuf;

public interface ResponseAnimalsInProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseAnimalsInProduct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated uint32 animal_ids = 1;</code>
   * @return A list containing the animalIds.
   */
  java.util.List<java.lang.Integer> getAnimalIdsList();
  /**
   * <code>repeated uint32 animal_ids = 1;</code>
   * @return The count of animalIds.
   */
  int getAnimalIdsCount();
  /**
   * <code>repeated uint32 animal_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The animalIds at the given index.
   */
  int getAnimalIds(int index);
}
