// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.grpcspringbootx.protobuf;

public final class SlaughterhouseOuterClass {
  private SlaughterhouseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestAnimalsInProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestAnimalsInProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseAnimalsInProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseAnimalsInProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestProductsWithAnimal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestProductsWithAnimal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseProductsWithAnimal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseProductsWithAnimal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024Slaughterhouse.proto\"%\n\027RequestAnimals" +
      "InProduct\022\n\n\002id\030\001 \001(\r\".\n\030ResponseAnimals" +
      "InProduct\022\022\n\nanimal_ids\030\001 \003(\r\"\'\n\031Request" +
      "ProductsWithAnimal\022\n\n\002id\030\001 \001(\r\"1\n\032Respon" +
      "seProductsWithAnimal\022\023\n\013product_ids\030\001 \003(" +
      "\r2\262\001\n\016Slaughterhouse\022L\n\025getAnimalIdsOfPr" +
      "oduct\022\030.RequestAnimalsInProduct\032\031.Respon" +
      "seAnimalsInProduct\022R\n\027getProductIdsWithA" +
      "nimal\022\032.RequestProductsWithAnimal\032\033.Resp" +
      "onseProductsWithAnimalB%\n!via.sdj3.grpcs" +
      "pringbootx.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RequestAnimalsInProduct_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestAnimalsInProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestAnimalsInProduct_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ResponseAnimalsInProduct_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseAnimalsInProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseAnimalsInProduct_descriptor,
        new java.lang.String[] { "AnimalIds", });
    internal_static_RequestProductsWithAnimal_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RequestProductsWithAnimal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestProductsWithAnimal_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ResponseProductsWithAnimal_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ResponseProductsWithAnimal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseProductsWithAnimal_descriptor,
        new java.lang.String[] { "ProductIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
